version: "2"
services:
  dummyappx:
    build: ./image
    ports:
      - "80:81"
      - "443:443"
    volumes:
      - ./src:/var/www/dummyapp
    networks:
      - dummyapp_default

networks:
  dummyapp_default:
    driver: bridge

